name: Build and publish Doxygen documentation to MSI documentation server
run-name: ${{ gitea.actor }} is attempting to build and upload the Doxygen documentation...
on: [push]

jobs:
  build:
    runs-on: windows
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: 'master'
          sparse-checkout: |
            .gitea/
            COVERT/
            COVERT_flight/
            CovertICP/
            ListenerLib/
            ListenerLibLite/
            pch/
            resources/
            Doxyfile
            README.md
      - name: Build documentation
        run: |
          doxygen Doxyfile
      - name: Publish documentation
        run: |
          cd docs
          Rename-Item -Path "html" -NewName "COVERT-Cpp"
          robocopy COVERT-Cpp C:\GiteaDocs\HTTPServer\COVERT-Cpp /mir
        continue-on-error: true
